import Head from 'next/head'

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Ritesh Kumar</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </>
    )
}

export default Layout